// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// ); ff
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcFNo7ref6AI94SpgSWIMQvsPRNwWhwDI',
    appId: '1:191306925703:android:252e41bcdc25b844021a22',
    messagingSenderId: '191306925703',
    projectId: 'harilalaina-fifaliana',
    databaseURL: 'https://harilalaina-fifaliana-default-rtdb.firebaseio.com',
    storageBucket: 'harilalaina-fifaliana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvSgwzVGg1is4Wt3oBvEc_KtCddzkQi_g',
    appId: '1:191306925703:ios:d5977bb92d8a4a33021a22',
    messagingSenderId: '191306925703',
    projectId: 'harilalaina-fifaliana',
    databaseURL: 'https://harilalaina-fifaliana-default-rtdb.firebaseio.com',
    storageBucket: 'harilalaina-fifaliana.firebasestorage.app',
    iosBundleId: 'com.culinaryevolution.culinaryevolutionapp',
  );
}
